const cards = [
  [{
    title: 'Animals 1',
    img: '../src/assets/img/horse.jpg',
    index: 0,
    isVisibleInMenu: true,
  },
  {
    title: 'Animals 2',
    img: '../src/assets/img/turtle.jpg',
    index: 1,
    isVisibleInMenu: true,
  },
  {
    title: 'Clothes',
    img: '../src/assets/img/blouse.jpg',
    index: 2,
    isVisibleInMenu: true,
  },
  {
    title: 'Emotions',
    img: '../src/assets/img/happy.jpg',
    index: 3,
    isVisibleInMenu: true,
  },
  {
    title: 'Vegetables',
    img: '../src/assets/img/pumpkin.jpg',
    index: 4,
    isVisibleInMenu: true,
  },
  {
    title: 'Fruits',
    img: '../src/assets/img/banana.jpg',
    index: 5,
    isVisibleInMenu: true,
  },
  {
    title: 'Nature',
    img: '../src/assets/img/forest.jpg',
    index: 6,
    isVisibleInMenu: true,
  },
  {
    title: 'City',
    img: '../src/assets/img/road.jpg',
    index: 7,
    isVisibleInMenu: true,
  },
  {
    title: 'Repeat',
    img: '',
    index: 8,
    isVisibleInMenu: false,
  },
  ],
  [
    [
      {
        category: 'Animals 1',
        word: 'cat',
        translation: 'кот',
        image: '../src/assets/img/cat.jpg',
        audioSrc: '../src/assets/audio/cat.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 1',
        word: 'chick',
        translation: 'цыплёнок',
        image: '../src/assets/img/chick.jpg',
        audioSrc: '../src/assets/audio/chick.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 1',
        word: 'chicken',
        translation: 'курица',
        image: '../src/assets/img/chicken.jpg',
        audioSrc: '../src/assets/audio/chicken.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 1',
        word: 'dog',
        translation: 'собака',
        image: '../src/assets/img/dog.jpg',
        audioSrc: '../src/assets/audio/dog.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 1',
        word: 'horse',
        translation: 'лошадь',
        image: '../src/assets/img/horse.jpg',
        audioSrc: '../src/assets/audio/horse.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 1',
        word: 'pig',
        translation: 'свинья',
        image: '../src/assets/img/pig.jpg',
        audioSrc: '../src/assets/audio/pig.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 1',
        word: 'rabbit',
        translation: 'кролик',
        image: '../src/assets/img/rabbit.jpg',
        audioSrc: '../src/assets/audio/rabbit.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 1',
        word: 'sheep',
        translation: 'овца',
        image: '../src/assets/img/sheep.jpg',
        audioSrc: '../src/assets/audio/sheep.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
      {
        category: 'Animals 2',
        word: 'bird',
        translation: 'птица',
        image: '../src/assets/img/bird.jpg',
        audioSrc: '../src/assets/audio/bird.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 2',
        word: 'fish',
        translation: 'рыба',
        image: '../src/assets/img/fish1.jpg',
        audioSrc: '../src/assets/audio/fish.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 2',
        word: 'frog',
        translation: 'жаба',
        image: '../src/assets/img/frog.jpg',
        audioSrc: '../src/assets/audio/frog.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 2',
        word: 'giraffe',
        translation: 'жирафа',
        image: '../src/assets/img/giraffe.jpg',
        audioSrc: '../src/assets/audio/giraffe.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 2',
        word: 'lion',
        translation: 'лев',
        image: '../src/assets/img/lion.jpg',
        audioSrc: '../src/assets/audio/lion.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 2',
        word: 'mouse',
        translation: 'мышь',
        image: '../src/assets/img/mouse.jpg',
        audioSrc: '../src/assets/audio/mouse.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 2',
        word: 'turtle',
        translation: 'черепаха',
        image: '../src/assets/img/turtle.jpg',
        audioSrc: '../src/assets/audio/turtle.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Animals 2',
        word: 'dolphin',
        translation: 'дельфин',
        image: '../src/assets/img/dolphin.jpg',
        audioSrc: '../src/assets/audio/dolphin.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
      {
        category: 'Clothes',
        word: 'skirt',
        translation: 'юбка',
        image: '../src/assets/img/skirt.jpg',
        audioSrc: '../src/assets/audio/skirt.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Clothes',
        word: 'pants',
        translation: 'брюки',
        image: '../src/assets/img/pants.jpg',
        audioSrc: '../src/assets/audio/pants.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Clothes',
        word: 'blouse',
        translation: 'блузка',
        image: '../src/assets/img/blouse.jpg',
        audioSrc: '../src/assets/audio/blouse.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Clothes',
        word: 'dress',
        translation: 'платье',
        image: '../src/assets/img/dress.jpg',
        audioSrc: '../src/assets/audio/dress.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Clothes',
        word: 'boot',
        translation: 'ботинок',
        image: '../src/assets/img/boot.jpg',
        audioSrc: '../src/assets/audio/boot.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Clothes',
        word: 'shirt',
        translation: 'рубашка',
        image: '../src/assets/img/shirt.jpg',
        audioSrc: '../src/assets/audio/shirt.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Clothes',
        word: 'coat',
        translation: 'пальто',
        image: '../src/assets/img/coat.jpg',
        audioSrc: '../src/assets/audio/coat.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Clothes',
        word: 'shoe',
        translation: 'туфли',
        image: '../src/assets/img/shoe.jpg',
        audioSrc: '../src/assets/audio/shoe.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
      {
        category: 'Emotions',
        word: 'sad',
        translation: 'грустный',
        image: '../src/assets/img/sad.jpg',
        audioSrc: '../src/assets/audio/sad.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Emotions',
        word: 'angry',
        translation: 'сердитый',
        image: '../src/assets/img/angry.jpg',
        audioSrc: '../src/assets/audio/angry.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Emotions',
        word: 'happy',
        translation: 'счастливый',
        image: '../src/assets/img/happy.jpg',
        audioSrc: '../src/assets/audio/happy.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Emotions',
        word: 'tired',
        translation: 'уставший',
        image: '../src/assets/img/tired.jpg',
        audioSrc: '../src/assets/audio/tired.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Emotions',
        word: 'surprised',
        translation: 'удивлённый',
        image: '../src/assets/img/surprised.jpg',
        audioSrc: '../src/assets/audio/surprised.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Emotions',
        word: 'scared',
        translation: 'испуганный',
        image: '../src/assets/img/scared.jpg',
        audioSrc: '../src/assets/audio/scared.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Emotions',
        word: 'smile',
        translation: 'улыбка',
        image: '../src/assets/img/smile.jpg',
        audioSrc: '../src/assets/audio/smile.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Emotions',
        word: 'laugh',
        translation: 'смех',
        image: '../src/assets/img/laugh.jpg',
        audioSrc: '../src/assets/audio/laugh.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
      {
        category: 'Vegetables',
        word: 'avocado',
        translation: 'авокадо',
        image: '../src/assets/img/avocado.jpg',
        audioSrc: '../src/assets/audio/avocado.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Vegetables',
        word: 'carrot',
        translation: 'морковь',
        image: '../src/assets/img/carrot.jpg',
        audioSrc: '../src/assets/audio/carrot.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Vegetables',
        word: 'onion',
        translation: 'лук',
        image: '../src/assets/img/onion.jpg',
        audioSrc: '../src/assets/audio/onion.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Vegetables',
        word: 'tomato',
        translation: 'томат',
        image: '../src/assets/img/tomato.jpg',
        audioSrc: '../src/assets/audio/tomato.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Vegetables',
        word: 'cabbage',
        translation: 'капуста',
        image: '../src/assets/img/cabbage.jpg',
        audioSrc: '../src/assets/audio/cabbage.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Vegetables',
        word: 'pumpkin',
        translation: 'тыква',
        image: '../src/assets/img/pumpkin.jpg',
        audioSrc: '../src/assets/audio/pumpkin.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Vegetables',
        word: 'eggplant',
        translation: 'баклажан',
        image: '../src/assets/img/eggplant.jpg',
        audioSrc: '../src/assets/audio/eggplant.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Vegetables',
        word: 'zucchini',
        translation: 'цукини',
        image: '../src/assets/img/zucchini.jpg',
        audioSrc: '../src/assets/audio/zucchini.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
      {
        category: 'Fruits',
        word: 'orange',
        translation: 'апельсин',
        image: '../src/assets/img/orange.jpg',
        audioSrc: '../src/assets/audio/orange.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Fruits',
        word: 'grapes',
        translation: 'виноград',
        image: '../src/assets/img/grapes.jpg',
        audioSrc: '../src/assets/audio/grapes.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Fruits',
        word: 'banana',
        translation: 'банан',
        image: '../src/assets/img/banana.jpg',
        audioSrc: '../src/assets/audio/banana.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Fruits',
        word: 'pineapple',
        translation: 'ананас',
        image: '../src/assets/img/pineapple.jpg',
        audioSrc: '../src/assets/audio/pineapple.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Fruits',
        word: 'persimmon',
        translation: 'хурма',
        image: '../src/assets/img/persimmon.jpg',
        audioSrc: '../src/assets/audio/persimmon.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Fruits',
        word: 'mango',
        translation: 'манго',
        image: '../src/assets/img/mango.jpg',
        audioSrc: '../src/assets/audio/mango.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Fruits',
        word: 'apple',
        translation: 'яблоко',
        image: '../src/assets/img/apple.jpg',
        audioSrc: '../src/assets/audio/apple.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Fruits',
        word: 'pear',
        translation: 'груша',
        image: '../src/assets/img/pear.jpg',
        audioSrc: '../src/assets/audio/pear.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
      {
        category: 'Nature',
        word: 'forest',
        translation: 'лес',
        image: '../src/assets/img/forest.jpg',
        audioSrc: '../src/assets/audio/forest.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Nature',
        word: 'beach',
        translation: 'пляж',
        image: '../src/assets/img/beach.jpg',
        audioSrc: '../src/assets/audio/beach.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Nature',
        word: 'snow',
        translation: 'снег',
        image: '../src/assets/img/snow.jpg',
        audioSrc: '../src/assets/audio/snow.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Nature',
        word: 'desert',
        translation: 'пустыня',
        image: '../src/assets/img/desert.jpg',
        audioSrc: '../src/assets/audio/desert.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Nature',
        word: 'rainbow',
        translation: 'радуга',
        image: '../src/assets/img/rainbow.jpg',
        audioSrc: '../src/assets/audio/rainbow.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Nature',
        word: 'mountain',
        translation: 'гора',
        image: '../src/assets/img/mountain.jpg',
        audioSrc: '../src/assets/audio/mountain.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Nature',
        word: 'grass',
        translation: 'трава',
        image: '../src/assets/img/grass.jpeg',
        audioSrc: '../src/assets/audio/grass.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'Nature',
        word: 'cloud',
        translation: 'облако',
        image: '../src/assets/img/cloud.jpg',
        audioSrc: '../src/assets/audio/cloud.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
      {
        category: 'City',
        word: 'road',
        translation: 'дорога',
        image: '../src/assets/img/road.jpg',
        audioSrc: '../src/assets/audio/road.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'City',
        word: 'building',
        translation: 'здание',
        image: '../src/assets/img/building.jpg',
        audioSrc: '../src/assets/audio/building.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'City',
        word: 'crossroad',
        translation: 'перекресток',
        image: '../src/assets/img/crossroad.jpg',
        audioSrc: '../src/assets/audio/crossroad.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'City',
        word: 'store',
        translation: 'магазин',
        image: '../src/assets/img/store.jpg',
        audioSrc: '../src/assets/audio/store.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'City',
        word: 'car',
        translation: 'машина',
        image: '../src/assets/img/car.jpg',
        audioSrc: '../src/assets/audio/car.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'City',
        word: 'bus',
        translation: 'автобус',
        image: '../src/assets/img/bus.jpg',
        audioSrc: '../src/assets/audio/bus.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'City',
        word: 'bench',
        translation: 'скамейка',
        image: '../src/assets/img/bench.jpg',
        audioSrc: '../src/assets/audio/bench.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
      {
        category: 'City',
        word: 'theatre',
        translation: 'театр',
        image: '../src/assets/img/theatre.jpg',
        audioSrc: '../src/assets/audio/theatre.mp3',
        trained: 0,
        correct: 0,
        errors: 0,
        '%': 0,
      },
    ],
    [
    ],
  ],
];

export default cards;
